# 「檢查專案中的潛在問題」GitHub 工作流程(workflow)定義檔
#
# 編輯參考：
#
# * Workflow syntax for GitHub Actions - GitHub Docs
#   https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
name: 檢查專案中的潛在問題
on:
  - push
jobs:
  check-using-precommit:
    name: 使用 pre-commit 檢查專案中的潛在問題
    runs-on: ubuntu-20.04
    steps:
      - name: 自版控庫取出內容
        uses: actions/checkout@v2
      - name: 安裝 pre-commit
        run: pip3 install pre-commit
      - name: 使用 pre-commit 檢查所有專案中的檔案
        run: pre-commit run --all-files
